### ISSUE TITLE
Home Page UI Improvements 

### ISSUE THREAD

**Issue by 9520prashant** [vedic-lang/vedic-lang.github.io#10]
**Describe the solution you'd like**

Hey @PtPrashantTripathi I think the original UI of Home Page is very basic, we can recreate or improve that Page by adding some cool stuffs like: Shree Krishna animation. so that It will look cool as a new user we always think about the amazing UI of a website.

**Additional context**

I really want to contribute in such repo who represents our Indian culture, I have that much ability to improve the UI. can you assign me this feature request to improve the UI of Home Section of Vedic-lang site.

**Comment by PtPrashantTripathi** [comment]
I have added you in organisation please accept the request

**Comment by rituraj00** [comment]
@9520prashant , @PtPrashantTripathi I love the project's concept, I would be glad to join you folks as contributor for web design as well as other enhancements.

**Comment by PtPrashantTripathi** [comment]
@rituraj00 added you as well

**Comment by 9520prashant** [comment]
> I have added you in organisation please accept the request

Thanks I have started working on it
