### ISSUE TITLE
instead of printing hello change it to Sanskrit word Namaste in hello-world.md

### ISSUE THREAD

**Issue by mohitkhatri06** [vedic-lang/vedic-lang.github.io#11]
**Is your feature request related to a problem? Please describe.**
As for now it is वद("हेलो विश्व!"); for hello world, hello is in English still

**Describe the solution you'd like**
instead of वद("हेलो विश्व!"); 
lets show it as वद("नमस्ते विश्व!");

**Comment by PtPrashantTripathi** [comment]
You can create a pr for your suggested edits I'll approve them
