### ISSUE TITLE
About Vedic 

### ISSUE THREAD

**Issue by Mitanshu-ui** [vedic-lang/vedic-lang.github.io#7]
**Suggestion :**
Hello there !!!  Kindly add "input" ( function from python ) or "scanf" (from c lang) etc in vedic lang as I not able to take input in my  program ❤️

**Comment by PtPrashantTripathi** [comment]
> **Suggestion :**
> Hello there !!!  Kindly add "input" ( function from python ) or "scanf" (from c lang) etc in vedic lang as I not able to take input in my  program ❤️

https://vedic-lang.github.io/native_functions.html#5-%E0%A4%AA%E0%A4%A0%E0%A4%A8-pathana

Yes we have पठन Function to take the user input
